### ISSUE TITLE
Query execution in elasticsearch.helpers.scan()

### ISSUE THREAD

**Issue by JaharshKotha** [elastic/elasticsearch-py#1023]
I am using the helpers.scan() to stream all documents from my AWS elasticsearch cluster, however I find that the query={} parameter is not respected and it returns all the documents from the cluster. 
My code: 
'''
iterableQuestions = elasticsearch.helpers.scan(es,index="index_name", preserve_order=True,query={"query": {"match": {"question_en": {
                                         "query": "Is it large enough to fit my elementary schooler's snow pants and winter coat in?"}}}})
'''

Version: 7.0.4

**Comment by HonzaKral** [comment]
I cannot replicate the issue, is it possible that the query is just too wide? since the default behavior of `match` query is to `or` all the terms together this will match on any documents that contain any of the words specified, including `it`, `is`, `to`, `and`, and `in` which are VERY common words.

Please feel free to reopen with additional information
