### ISSUE TITLE
cluster.state(index='name')['routing_table'] not found in client 7.5.1

### ISSUE THREAD

**Issue by untergeek** [elastic/elasticsearch-py#1141]
Using the most recent release of the Elasticsearch Python client (7.5.1 at this time), the cluster state endpoint is not defaulting to show `_all` keys.

### 7.5.1

```
client.cluster.state(index=idx).keys()
dict_keys(['cluster_name', 'cluster_uuid'])
```

### 7.1.1:

```
client.cluster.state(index=idx).keys()
dict_keys(['cluster_name', 'cluster_uuid', 'version', 'state_uuid', 'master_node', 'blocks', 'nodes', 'metadata', 'routing_table', 'routing_nodes'])
```

This omission, if intended, would seem to be something to change in a major release version, rather than a minor release.

This was detected and reported [here](https://github.com/elastic/support-dev-help/issues/10455#issue-558049925). This compels me to pin Curator at client version `elasticsearch==7.1.0` for now.

**Comment by sethmlarson** [comment]
Yeah this looks like a regression to me, previously there was logic that made `metric` into `_all` if an `index` was given by default but since the API is generated in ffe00d0c3899d200e640e33261d0a324e5dbb5ac it looks like that little piece of logic was lost.

Will have to investigate if any other little tidbits like that were lost as well.
