### ISSUE TITLE
Search is performing a POST request instead of a GET request after 7.6.0

### ISSUE THREAD

**Issue by menecio** [elastic/elasticsearch-py#1172]
**Description of the problem including expected versus actual behavior**:
With the release of `7.6.0` a big change in the `.search()` behavior was introduced, now it doesn't perform a `GET` request but a `POST` request, this affects credentials with Read-Only permissions resulting in `403 Forbidden` errors. 

Was this expected? If so, it should be mentioned in the changelog as a breaking change.

**Comment by sethmlarson** [comment]
Thank you for opening this. You're right this change should be mentioned in the changelog for 7.6.0.

The change from GET -> POST was made because the Python client is the only client that uses GET with an HTTP body (technically doesn't follow the HTTP spec) and all other clients use POST with a body. By chance is the query using a `body` parameter?

I'm surprised that endpoints determine whether a query is read-only based on method. I would not have assumed that, will find out more from other maintainers.

**Comment by menecio** [comment]
@sethmlarson thanks for the reply, yes I am doing the query using `body`, the code looks similar to this:
```python
hits = es.search(
    index=settings.ES_INDEX_PATTERN,
    doc_type="_doc",
    body={"query": query, "sort": [{"time": {"order": "desc", "unmapped_type": "boolean"}}]},
    size=api_settings.PAGE_SIZE,
    from_=page_number * api_settings.PAGE_SIZE,
)
```
We are using AWS Elasticsearch, so I wouldn't discard they implemented this security behavior in one of their layers.

**Comment by sethmlarson** [comment]
Sounds like AWS Elasticsearch is interpreting a POST as not read-only. :/

I guess your options are:
- Pinning to `elasticsearch==7.5.1`
- Adding write permissions to the API key
- Contacting AWS support and seeing if something can be done to fix the resource security?

Closing this as not a defect with the library. Let me know if you figure something out or hear anything more.
