### ISSUE TITLE
Error in documentation for es.search function

### ISSUE THREAD

**Issue by bfishh** [elastic/elasticsearch-py#1196]
In this doc:
https://elasticsearch-py.readthedocs.io/en/master/api.html#elasticsearch
for "serach" function offset parameter is named as "from" but in code it is "from_".
The name "from" is invalid and causes invalid syntax error.

**Comment by sethmlarson** [comment]
@bfishh Great catch, this looks to be an issue in our API generator. Would you be up to make this change?

**Comment by bfishh** [comment]
>Would you be up to make this change?
Not this time, sorry.

**Comment by bartier** [comment]
@sethmlarson Hi! Can I work on this? If yes, could you provide more information about how you would handle this issue?

`from` is a reserved keyword in Python, so I guess the documentation should be updated, right?

https://github.com/elastic/elasticsearch-py/blob/7dec9e3dbaabb2b7cc5cdb1a49370c89de72fa12/elasticsearch/client/__init__.py#L702-L704

I would propose something like this in the  docs:
![image](https://user-images.githubusercontent.com/18057391/79622008-e7a15000-80eb-11ea-9301-019141acaec1.png)


Reference link to actual content: https://elasticsearch-py.readthedocs.io/en/master/api.html#elasticsearch.Elasticsearch.search

The actual docs is wrong because `_` needs a back slash `\` to be rendered:

Actual code:
https://github.com/elastic/elasticsearch-py/blob/7dec9e3dbaabb2b7cc5cdb1a49370c89de72fa12/elasticsearch/client/__init__.py#L656

Code that would work:
```
        :arg from\_: Starting offset (default: 0)
                     ``from`` is a reserved keyword in Python. In order to avoid a syntax error this function uses ``from_``
```

Is this a valid solution? If yes, can I send a PR? :)

**Comment by sethmlarson** [comment]
@bartier That would be great! You'll have to make the change within the `utils/` directory as all of the code including docstrings under `elasticsearch/clients/`  is generated from `utils/generate_api.py`

You can take a look at the commit history of that file for examples :)

Let me know if you run into problems or have questions, I'm here to help! :D

**Comment by bartier** [comment]
@sethmlarson Thanks for answering me :D

I sent my a PR (first one here!) that attempts to solve this issue. Could you check it if it is a valid solution?
