### ISSUE TITLE
scan api fails with authorization error with Amazon ES

### ISSUE THREAD

**Issue by rjaiwal5139** [elastic/elasticsearch-py#1425]
**Elasticsearch version** (`bin/elasticsearch --version`):  7.4.2

**`elasticsearch-py` version (`elasticsearch.__versionstr__`)**:  7.9.1

Please make sure the major version matches the Elasticsearch server you are running.

**Description of the problem including expected versus actual behavior**: 

When using the scan api (with no size argument)with Amazon Elasticsearch, get this error: elasticsearch.exceptions.AuthorizationException: AuthorizationException(403, u'{"Message":"User: anonymous is not authorized to perform: es:ESHttpDelete"}'). 

When set clear_scroll to false, get this error: elasticsearch.exceptions.AuthorizationException: AuthorizationException(403, u'{"Message":"User: anonymous is not authorized to perform: es:ESHttpPost"}'). 

**Steps to reproduce**:

1. Instantiate es client
2. Use scan api to get back a generator
3. Iterate the generator, at the last iteration, fails with above error.

**Comment by sethmlarson** [comment]
The Elasticsearch clients go through rigorous testing and validation against the official Elasticsearch distribution coming from Elastic. Since the AWS Elasticsearch Service has incompatible APIs with Elasticsearch itself, either by missing APIs or has incompatible format, we do not support it. Please consider using [Elastic Cloud](https://cloud.elastic.co/) for an official and formally supported hosted Elasticsearch distribution.
