### ISSUE TITLE
Document type stubs, usage, and best practices

### ISSUE THREAD

**Issue by jacksmith15** [elastic/elasticsearch-py#1435]
**Elasticsearch version**: N/A (python-specific)

**`elasticsearch-py` version**: 7.10.0

Please make sure the major version matches the Elasticsearch server you are running.

**Description of the problem including expected versus actual behavior**:

Newly introduced type stubs (whilst extremely welcome) contain a few errors. To point out an example:

Ignoring all arguments besides `repository` and `body` for simplicity, `SnapshotClient.create_repository` accepts two positional arguments in its implementation, however the stub only accepts one:

Actual signature:
```python
def create_repository(self, repository, body):
    ...
```

Type stub signature:
```python
def create_repository(self, repository: Any, *, body: Any):
```

This means that the following existing code will incorrectly raise errors in a type-checker:

```python
client.snapshot.create_repository("repository", "body")
# error: Too many positional arguments for "create_repository" of "SnapshotClient"
```

I have observed a similar issue on `SlmClient.put_lifecycle`, it is possible there are others.

**Steps to reproduce**:

Run a typechecker such as `mypy` on the code above, and receive the same error.

**Comment by sethmlarson** [comment]
Functionally yes the type hint doesn't exactly match the signature, however I chose to make body arguments keyword only because there's a non-zero chance in the future that an API makes the body parameter optional where previously it was required.

This wouldn't be a breaking change on the Elasticsearch side but would require manual mitigation on the client side to avoid changing parameter order. Using keyword arguments is a best practice and makes sure your code will continue to work across versions so I've codified it in the type hints.

Also whenever we're able to safely drop Python 2 (no time soon likely) I'd like to require keyword arguments, so starting to push lightly them now is for the best.

Does this answer your question?

**Comment by jacksmith15** [comment]
It does indeed! This might be worth a shout-out in the Changelog, as it took a bit of digging in the source code to discern that my `mypy` failures after upgrading the library weren't due to an actual breaking change in the library.

**Comment by sethmlarson** [comment]
Good idea, I also want to devote a section of the documentation to using Mypy and Pyright, etc with the library.

**Comment by sethmlarson** [comment]
These have been documented in #1439, thanks for raising this issue!
