### ISSUE TITLE
http_auth handling within AIOHttpRequest

### ISSUE THREAD

**Issue by jfrance1** [elastic/elasticsearch-py#1593]
Is there a specific reason why AIOHTTPRequest handles http_auth differently than RequestsHTTPRequest?

**Comment by sethmlarson** [comment]
Yes, `http_auth` for `Urllib3HttpConnection` and `AIOHttpConnection` are only handled a username and password tuple as is documented. For `RequestsHttpConnection` the `http_auth` parameter is passed directly to the `requests.Session` object and so are handled in a special way if they are objects that have special behavior for the `requests` library.

Basically you're getting special undocumented behavior because the `RequestsHttpConnection` uses `requests` behind the curtains.

Does this answer your question?

**Comment by jfrance1** [comment]
Yes.  I asked because I would like to sign my http calls to AWS services, specifically AWS Elasticsearch.  So far have the only library I have come across is https://github.com/tedder/requests-aws4auth, which works fine with RequestsHttpConnection but not AIOHttpConnection.
