### ISSUE TITLE
AIOHttpConnection support for Signature Version 4 signing

### ISSUE THREAD

**Issue by jfrance1** [elastic/elasticsearch-py#1594]
https://docs.aws.amazon.com/general/latest/gr/signature-version-4.html

RequestsHttpConnection is able to use https://github.com/tedder/requests-aws4auth however AIOHttpConnection does not support signature version 4.

**Comment by sethmlarson** [comment]
The Elasticsearch clients go through rigorous testing and validation against the official Elasticsearch distribution coming from Elastic. Since the AWS Elasticsearch Service has incompatible APIs with Elasticsearch itself, either by missing APIs or has incompatible format, we do not support it. Please consider using [Elastic Cloud](https://cloud.elastic.co/) for an official and formally supported hosted Elasticsearch distribution.
