### ISSUE TITLE
Unable to connect to the AWS elasticsearch fine-grained access with master-username and password

### ISSUE THREAD

**Issue by Tushar19varshney** [elastic/elasticsearch-py#1615]
**Describe the feature**:
I am not able to connect to the AWS elasticsearch instance using fine-grained access control which requires master username and master password for authentication. How can I pass username and password also for accessing the elasticsearch.

```
host = ''
service = ''
credentials = boto3.Session().get_credentials()
awsauth = AWS4Auth(credentials.access_key, credentials.secret_key, region, service, session_token=credentials.token)

es = Elasticsearch(
     hosts=[{'host': host, 'port': 443}],
     http_auth=awsauth,
     use_ssl=True,
     verify_certs=True,
     connection_class=RequestsHttpConnection
    )
print(es.info())
```

**Elasticsearch version** (`bin/elasticsearch --version`):

**`elasticsearch-py` version (`elasticsearch.__versionstr__`)**: 

Please make sure the major version matches the Elasticsearch server you are running.

**Description of the problem including expected versus actual behavior**:

`AuthorizationException: AuthorizationException(403, 'security_exception', 'no permissions for [cluster:monitor/main] and User [name=arn:aws:iam::647348057521:root, backend_roles=[], requestedTenant=null]')`

**Comment by sethmlarson** [comment]
The Elasticsearch clients go through rigorous testing and validation against the official Elasticsearch distribution coming from Elastic. Since the AWS Elasticsearch Service has incompatible APIs with Elasticsearch itself, either by missing APIs or has incompatible format, we do not support it. Please consider using [Elastic Cloud](https://cloud.elastic.co/) for an official and formally supported hosted Elasticsearch distribution.
