### ISSUE TITLE
UnsupportedProductError with AWS ElasticSearch Service

### ISSUE THREAD

**Issue by sbds** [elastic/elasticsearch-py#1667]
Starting yesterday I'm receiving UnsupportedProductError when bulk writing against an AWS ElasticSearch v7.10 domain.

**Comment by sethmlarson** [comment]
The Elasticsearch clients go through rigorous testing and validation against the official Elasticsearch distribution coming from Elastic. Since the AWS Elasticsearch Service has incompatible APIs with Elasticsearch itself, either by missing APIs or has incompatible format, we do not support it. Please consider using [Elastic Cloud](https://cloud.elastic.co/) for an official and formally supported hosted Elasticsearch distribution.

**Comment by sbds** [comment]
Sure, I'll move my whole stack to satisfy your little client. Good luck promoting that.

**Comment by atsalolikhin-spokeo** [comment]
See also https://github.com/elastic/elasticsearch-py/issues/1666

**Comment by iamthen0ise** [comment]
@sbds I can understand your pain. Also had to fix it by myself when AWS bumped client to latest. What I did — pin AWS 7.9 and client 7.11 and plan moving my Search from AWS in  f/w 21-22 :(

**Comment by burkel24** [comment]
Is it really okay to make a change like this in a minor version update? Feels like a huge breaking change to me. And with no option to opt out of this check no less?

Hard not to feel like you guys made this change because you didn't like AWS running a competing managed service. Really not a good look
