### ISSUE TITLE
reindex() with random sampling always returns the same documents

### ISSUE THREAD

**Issue by konstantinmiller** [elastic/elasticsearch-py#1674]
Elasticsearch version: 7.12.0

`elasticsearch-py` version: 7.13.1

`reindex()` with random sampling always returns the same documents, irrespective of the seed

Steps to reproduce:

```
query = {
    'function_score': {
        'query': {'match_all': {}},
        'random_score': {},
    }
}

request_body = {
    'source': {
        'index': source_index,
        'query': query,
    },
    'dest': {
        'index': destination_index,
    }
}

es.reindex(body=request_body, refresh=True, max_docs=number_of_samples)
```

**Comment by sethmlarson** [comment]
Great question, thanks for opening this! So even without a `seed` given to the `random_score` function will use [Lucene document IDs](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-function-score-query.html#function-random) as it's source of randomness which isn't "random" in the way that you want (you want randomness between separate calls to the API, not just random on any given API call due to merges)

So what can you do to achieve the behavior you want? My suggestion would be to generate the seed randomly per API request with something like [`secrets.randbits()`](https://docs.python.org/3/library/secrets.html#secrets.randbits)

In the end your query will look like this (for 32 bits of randomness):

```python
import secrets

query = {
    'function_score': {
        'query': {'match_all': {}},
        'random_score': {
            'seed': secrets.randbits(32),
            'field': '_seq_no'
        },
    }
}

request_body = {
    'source': {
        'index': source_index,
        'query': query,
    },
    'dest': {
        'index': destination_index,
    }
}

es.reindex(body=request_body, refresh=True, max_docs=number_of_samples)
```

Does this answer your question?

**Comment by sethmlarson** [comment]
Closing this as solved, let me know if there's additional questions.

**Comment by konstantinmiller** [comment]
Thanks! I think I was confused by an older version of the documentation which stated that the default seed would be the timestamp so that it still would work and be random. Or maybe I just confused it with entirely something else.

However, explicitly setting the seed and using `_seq_no` for the field parameter still doesn't produce the expected outcome. If I set `max_docs` to one, I still always get exactly the same document in the new index.
