### ISSUE TITLE
slowdown since 7.14.0

### ISSUE THREAD

**Issue by lijok** [elastic/elasticsearch-py#1676]
in https://github.com/elastic/elasticsearch-py/pull/1623 a preflight request was added to `/`
this has close to doubled response times for our aws lambda workflows
is there any official guidance on how to address this regression when it comes to short lived environments?
or is the only course of action to monkeypatch the validation and turn it off?

**Comment by sethmlarson** [comment]
There isn't a way to disable the product check aside from the route you mentioned. The [`info` API](https://www.elastic.co/guide/en/elasticsearch/reference/current/info-api.html) is very quick to respond as no computation is done aside from sending version information so shouldn't impact request latencies beyond a single RTT.

**Comment by lijok** [comment]
> There isn't a way to disable the product check aside from the route you mentioned. The `info` API is very quick to respond as no computation is done aside from sending version information so shouldn't impact request latencies beyond a single RTT.

could a flag be added to disable product check?

**Comment by sethmlarson** [comment]
There won't be a flag added to disable the product check for 7.x. In 8.x the product check will not use a pre-flight request.

**Comment by lijok** [comment]
> There won't be a flag added to disable the product check for 7.x. In 8.x the product check will not use a pre-flight request.

What's the rationale behind not adding a flag for disabling the product check?
If the intention behind the change in the linked PR is to reduce number of issues raised to the repo due to someone using the library with an incompatible product, then that stance doesn't make much sense to me. A flag would indicate the user understands what they're doing and understands that the system they're using this library with may be incompatible.
As it stands right now, v7.14.0 kills the performance of our service running on aws lambda
Our responses from lambdas that arent in the same region as the cluster have gone from taking 1.4s on average to 2.2s, which doesn't fly under the radar

**Comment by OriHoch** [comment]
I added a PR which implements this: https://github.com/elastic/elasticsearch-py/pull/1678

**Comment by OriHoch** [comment]
See the following code to easily disable the product check: 

https://github.com/OriHoch/elasticsearch-py-disable-product-check/blob/main/example-success.py

**Comment by kimchy** [comment]
@lijok quick answer on my end, the team is looking into it, obviously we would make sure there isn’t performance regression. Obviously we would consider a flag, though would like to find a way to solve it differently. Here is why:

We have significant amount of users and customers failing with these clients running against AWS ES and now OpenSearch. OpenSearch for example causes more than a third of the python client tests fail. We are facing a difficult situation here, made harder by the Amazon team trying to still use the Elasticsearch brand as long as possible even after a fork, as they have for some time now. Sadly, I expect this persistence of abuse to continue based on past behavior. Wished it was different.

I can assure you, that for us, our foremost concern is our customers and users. We are trying to balance the hard decision of not letting our users face unexpected failures, which we see hundreds of on a daily basis, due to the misleading messaging we see with Amazon. Vs. what you see here. And while we try to be clear with our communication, like with this change when we blogged about it, we will continue to do more as much as we possible. Thank you for the understanding while we figure it out.

**Comment by lijok** [comment]
> @lijok quick answer on my end, the team is looking into it, obviously we would make sure there isn’t performance regression. Obviously we would consider a flag, though would like to find a way to solve it differently. Here is why:
> 
> We have significant amount of users and customers failing with these clients running against AWS ES and now OpenSearch. OpenSearch for example causes more than a third of the python client tests fail. We are facing a difficult situation here, made harder by the Amazon team trying to still use the Elasticsearch brand as long as possible even after a fork, as they have for some time now. Sadly, I expect this persistence of abuse to continue based on past behavior. Wished it was different.
> 
> I can assure you, that for us, our foremost concern is our customers and users. We are trying to balance the hard decision of not letting our users face unexpected failures, which we see hundreds of on a daily basis, due to the misleading messaging we see with Amazon. Vs. what you see here. And while we try to be clear with our communication, like with this change when we blogged about it, we will continue to do more as much as we possible. Thank you for the understanding while we figure it out.

That makes it much clearer
Thank you for the prompt response

**Comment by philkra** [comment]
Thanks for your patience - as @kimchy noted, we take issues like this seriously. And in doing so, we realized that we hadn't provided clear best practices for using our clients in Function-as-a-Service environments. We have now updated our [documentation](https://www.elastic.co/guide/en/elasticsearch/client/python-api/current/connecting.html#connecting-faas) to include best practices for using the Python client in the way that each Cloud provider recommends for connecting to databases/data stores. By following the cloud provider best practices, you can eliminate the additional roundtrip, and also reduce overhead for a number of other interactions with Elasticsearch.
