### ISSUE TITLE
UnsupportedProductError BLOCKER

### ISSUE THREAD

**Issue by gguta** [elastic/elasticsearch-py#1768]
After one of the minor version update the client stopped working with "elasticsearch.exceptions.UnsupportedProductError: The client noticed that the server is not Elasticsearch and we do not support this unknown product" error message. Please, revert this changes IMMEDIATELY to a simple warning message. If you worry about quality problems this is more than enough solution and let your customer decided what he wants to do. (Releasing this change in this form is completely unacceptable. It is against the general policy that you do not introduce BREAKING changes in minor releases. I'm also sure we are not the only client of Elasticsearch B.V. to whom this change cause deployment problems (i.e. financially quantifiable damage).

**Comment by AndrewFarley** [comment]
Yeah, I need to pile on some comment thread about this issue since the admins of this codebase keep (curiously) closing comments to communicate that this is an underhanded and childish thing to do in an open-source community.  This isn't how open source works guys, you should know that.  This makes you look bad, and will only make people want to use your "official" products less.  Thanks for making this choice easy, guys.

**Comment by AndrewFarley** [comment]
I'd love to see if/when someone forks your codebase (automatically) to simply remove this "error" and re-publish the pip package as perhaps `elasticsearch-py-fixed`.  Anyone up to the task?
