### ISSUE TITLE
Mismatch between code and stubs on Elasticsearch.index

### ISSUE THREAD

**Issue by elip-OE** [elastic/elasticsearch-py#1811]
**Elasticsearch version** (`bin/elasticsearch --version`):     7.12.1

**`elasticsearch-py` version (`elasticsearch.__versionstr__`)**:  7.15.2

Please make sure the major version matches the Elasticsearch server you are running.

**Description of the problem including expected versus actual behavior**:

There is mismatch between the code signature and the stubs:

https://github.com/elastic/elasticsearch-py/blob/v7.15.2/elasticsearch/client/__init__.py#L360

```
    def index(self, index, body, doc_type=None, id=None, params=None, headers=None):
```

https://github.com/elastic/elasticsearch-py/blob/v7.15.2/elasticsearch/client/__init__.pyi#L183-L187

```
    def index(
        self,
        *,
        index: str,
        document: Any,
        ...
    )
```

since the stubs matches the 8.x API, I'm guessing this is related to some auto-generated code.

**Steps to reproduce**:

N/A

**Comment by sethmlarson** [comment]
The stubs are correct, they aren't the same as the function signature because the `body` parameter is deprecated in 8.0 and onwards. You can either use `type: ignore` or switch to using `document=` with the `index` API. See this issue for more info on these deprecations: https://github.com/elastic/elasticsearch-py/issues/1698

Closing this for now, let me know if you have additional questions.
