### ISSUE TITLE
[Feature Request] List all pipelines using LogstashClient:get_pipeline.

### ISSUE THREAD

**Issue by aveuiller** [elastic/elasticsearch-py#1925]
It would be beneficial for us to be able to list all pipelines using the method LogstashClient:get_pipeline.
However, at the moment, [LogstashClient](https://github.com/elastic/elasticsearch-py/blob/main/elasticsearch/_sync/client/logstash.py#L82-L83) code requires a non-empty id as input.

This limitation could be easily removed to copy the behavior of [IngestClient](https://github.com/elastic/elasticsearch-py/blob/main/elasticsearch/_sync/client/ingest.py#L125-L128), _i.e._:
```python
        if id not in SKIP_IN_PATH:
            __path = f"/_ingest/pipeline/{_quote(id)}"
        else:
            __path = "/_ingest/pipeline"
```

Thanks!

**Comment by sethmlarson** [comment]
Thank you for reporting this, unfortunately the bug is elsewhere as the code you've linked to is generated automatically from API specs. I've submitted [a pull request](https://github.com/elastic/elasticsearch/pull/84150) to the API specs which will eventually trickle down to the client once released.

Going to close this one since there's nothing we can do here yet.
