### ISSUE TITLE
Bypass expired certificate

### ISSUE THREAD

**Issue by zapcity** [elastic/elasticsearch-py#1946]
Hi, I'm using v8.1.1 on Win10 and trying to connect to the ES cluster. The issue is an expired certificate on `https://myhost:443` is preventing me from connecting. I am able to connect to kibana using that URL via Chrome and Firefox. Both browsers complain that the certificate has expired. However with Chrome, it does allow me to proceed, although warning it's unsafe to do so. My attempt at connecting via python is as follows:

```
from elasticsearch import Elasticsearch
es = Elasticsearch('https://myhost:443', basic_auth=(myuser, mypwd))
print(es.info())
```

and I get:

`TlsError: TLS error caused by: TlsError(TLS error caused by: SSLError([SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1131)))`

I have also tried specifying `verify_certs=False` i.e. `Elasticsearch('https://myhost:443', basic_auth=(myuser, mypwd), verify_certs=False)`, however I get:

`SerializationError: Unable to deserialize as JSON: b''`

Is there a way around this? Is it possible to bypass a certificate verification if the certificate has expired? I would think so, as Chrome allows me to connect, however python doesn't. 

I understand that one step in this process is to fix the certificate itself, however that's out of my control, as it's administered by a separate unit in the organization which is taking it's time. Thanks for any help.

**Comment by pquentin** [comment]
The fact that you're receiving a `SerializationError` means that `verify_certs=False` worked.

I think the issue is that you're trying to connect to Kibana, which is a web application that answers requests with HTML. The Elasticsearch Python client connects to Elasticsearch, not Kibana. However, as mentioned when you opened your issues, GitHub is reserved for bug reports and feature requests. The best place to ask a general question is at the Elastic [forums](https://discuss.elastic.co). GitHub is not the place for general questions.
