### ISSUE TITLE
Get tasks when using slices - support parent_task_id

### ISSUE THREAD

**Issue by nelg** [elastic/elasticsearch-py#2055]
Please add support to pass in parent_task_id to get tasks, ideally with detailed=true.

So that when using slices, we can get all the subtasks.
https://elasticsearch-py.readthedocs.io/en/v8.4.0/api.html#elasticsearch.client.TasksClient.get

**Comment by miriam-eid** [comment]
Thank you for opening this! In order to get all the subtasks with the `parent_task_id` parameter, you should use [tasks.list](https://elasticsearch-py.readthedocs.io/en/v8.4.0/api.html#elasticsearch.client.TasksClient.list) instead of [tasks.get](https://elasticsearch-py.readthedocs.io/en/v8.4.0/api.html#elasticsearch.client.TasksClient.get).
 I'm closing this issue for now, let me know if you have any additional questions.
