### ISSUE TITLE
Docs use wrong parameter name for passing credentials

### ISSUE THREAD

**Issue by danielmitterdorfer** [elastic/elasticsearch-py#2169]
The docs in https://www.elastic.co/guide/en/elasticsearch/client/python-api/current/connecting.html (i.e. https://github.com/elastic/elasticsearch-py/blob/main/docs/guide/connecting.asciidoc) state that the constructor parameter to for passing credentials is called `basic_auth`. However, the correct parameter name is `http_auth`.

**Comment by sethmlarson** [comment]
For 8.x we added the semantic names `basic_auth` and `bearer_auth` instead of a generic `http_auth` that had different behavior depending on input type. We still support accepting `http_auth` but it's deprecated in favor of those two parameters.

See: https://github.com/elastic/elasticsearch-py/blob/main/elasticsearch/_sync/client/__init__.py#L135
