### ISSUE TITLE
Documentaion on how to configure trace logging

### ISSUE THREAD

**Issue by brandonmcclure** [elastic/elasticsearch-py#2221]
I am troubleshooting a query that is not working as expected in python, but I can run an equivalent query through my kibana ui.

The documentation for [logging](https://elasticsearch-py.readthedocs.io/en/v7.17.10/index.html?highlight=logging#logging) indicates that the `elasticsearch.trace` logger needs to be configured/activated to get the body of the web calls logged. I do not know how to configure this properly, and feel an example in the docs for how to configure this would be helpful for myself and others.

I am running code like what is below. I Set the log level to DEBUG for all, and then set propagate=True for the specific trace logger, but that does not seem to be what is needed to activate. I am still not seeing the body of the requests in the logs.
```
import logging
logging.basicConfig(level=logging.DEBUG, format='%(levelname)s || %(name)s.%(funcName)s:%(lineno)d || %(message)s')
logging.getLogger('elasticsearch.trace').propagate=True
```

and then running a query

```
es = Elasticsearch("http://localhost:9200")
es.search(index="myIndex", query=myQueryVar)
```

returns console logs like:

```console
DEBUG || urllib3.connectionpool._new_conn:228 || Starting new HTTP connection (1): localhost:9200
DEBUG || urllib3.connectionpool._make_request:456 || http://localhost:9200 "POST /git/_search HTTP/1.1" 200 111572
INFO || elastic_transport.transport.perform_request:336 || POST http://localhost:9200/git/_search [status:200 duration:0.004s]
```

**Comment by pquentin** [comment]
Hello! And sorry for the late answer.

The documentation you're linking to is about elasticsearch-py 7.17, but you're using version 8.x because your code is using https://github.com/elastic/elastic-transport-python/ which is the library that issues requests and logs them for verson 8.x. 

As a result, the relevant documentation is now at https://elastic-transport-python.readthedocs.io/en/latest/logging.html. You'll find the `debug_logging()` function very helpful.
