### ISSUE TITLE
problem in reindex

### ISSUE THREAD

**Issue by elimintz** [elastic/elasticsearch-py#2270]
https://github.com/elastic/elasticsearch-py/blob/18c5b705eaefbc60bb86eb85b7047e4bc54ec193/elasticsearch/_sync/client/__init__.py#L3189

The destination and source file for reindexing need to be assigned to lower level in dictionary.

Example of fix for dest:
__body["dest"] = {}
__body["dest"]["index"] = dest

**Comment by pquentin** [comment]
Hello!

The way this works is that you only use Python keyword arguments for the first level of keys, but then you can use normal dictionaries. This means you can use the reindex API this way:

```python3
es.reindex(
    source={"index": "index1"},
    dest={"index": "index2"},
)
```

I hope that helps. If you have more questions, feel free to ask them in the [language clients section of the Elastic forums](https://discuss.elastic.co/tag/language-clients). Since this is not an issue with the client itself, I'll go on and close the issue. Thanks!

**Comment by elimintz** [comment]
Thanks. This should be made clear in the documentation for reindex. As the documentation is written now, it is misleading.
