### ISSUE TITLE
es.bulk update only 50% of documents added

### ISSUE THREAD

**Issue by spenoir** [elastic/elasticsearch-py#228]
Bulk updates using the es.bulk method only add 50% of my documents. No matter how many I bulk update, only 50% seem to get added. Each time I bulk update it ignores different items too.

`es.bulk(body=es_data, index=INDEX_NAME, doc_type="document")`

However, the helpers.bulk method works fine, like this:

`helpers.bulk(es, es_data, index=INDEX_NAME, doc_type="document")`

Its kinda confusing having two methods that do the same thing so perhaps you should remove the one that doesn't seem to work?

**Comment by HonzaKral** [comment]
The `es.bulk` and `helpers.bulk` really don't do the same thing.

`helpers.bulk` is a convenience wrapper around the `es.bulk` which is, on its own, quite hard to use since you need to format the data according to the bulk format of elasticsearch (0).

Since this can largely be automated, we came up with the helper to make things simpler.

Could you please verify that your `es_data` you are passing to `es.bulk` are in the correct format?

Thanks!

0 - http://www.elastic.co/guide/en/elasticsearch/reference/current/docs-bulk.html#docs-bulk

**Comment by spenoir** [comment]
Would any documents get added if the json was in the wrong format? Using
helpers.bulk works fine so I assume my json is in the correct format, it
also looks correct.

cheers

**Comment by HonzaKral** [comment]
There is no way of telling without the data.

I am closing this issue since we found a solution, which is to just use the `helpers.bulk` function that takes care of the intricacies of the format.
