### ISSUE TITLE
Getting permission issue after upgrading to version 7.10

### ISSUE THREAD

**Issue by rashmiranjanbhoi** [elastic/elasticsearch-py#2363]
I am getting the below error after ES upgraded to version 7.10. Please let me know if there is any solution for this.

opensearchpy.exceptions.AuthorizationException: AuthorizationException(403, 'security_exception', 'no permissions for [indices:data/read/search] and User [name=arn:aws:iam::78***********:user/elastic-search/UserName, backend_roles=[], requestedTenant=null]')

**Comment by pquentin** [comment]
Hello! You appear to be using https://github.com/opensearch-project/opensearch-py - this repository is about the Elasticsearch Python client. In any case, you will need to provide more information than this to get help. Thanks.

**Comment by rashmiranjanbhoi** [comment]
Thank you for your response, but could you please explain the reason behind this error that I am seeing?

**Comment by rashmiranjanbhoi** [comment]
elasticsearch.exceptions.AuthorizationException: AuthorizationException(403, 'security_exception', 'no permissions for [cluster:monitor/main] and User [name=arn:aws:iam::123456789:user/elastic-search/username, backend_roles=[], requestedTenant=null]')

**Comment by pquentin** [comment]
Even if you're using the elasticsearch-py client in this snippet, you're still likely using the AWS OpenSearch server because I don't think Elasticsearch supports AWS Signature Version 4 which was designed for AWS services.

The Elasticsearch clients go through rigorous testing and validation against the official Elasticsearch distribution coming from Elastic. Since the AWS Elasticsearch Service has incompatible APIs with Elasticsearch itself, either by missing APIs or has incompatible format, we do not support it. Please consider using [Elastic Cloud](https://cloud.elastic.co/) for an official and formally supported hosted Elasticsearch distribution.

**Comment by rashmiranjanbhoi** [comment]
@pquentin Thank you
