### ISSUE TITLE
delete_by_query missing `source` parameter

### ISSUE THREAD

**Issue by barakcoh** [elastic/elasticsearch-py#238]
Hi

It looks like this parameter was removed in https://github.com/elastic/elasticsearch-py/commit/481dc907ad60e7e88bd16697e0e2c92ac56b99c2. While the entire [Delete By Query](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-delete-by-query.html) API was deprecated in `1.5.3`, it's still being used in our code base. Not sure why this specific parameter was removed as there's no indication that it's no longer valid (deprecation aside) and still necessary where issuing a `DELETE` request with a body is not possible (e.g. Google AppEngine).

**Comment by HonzaKral** [comment]
Ah, my bad - I tought only `GET` is broken on AppEngine.

In the short term you can use the workaround with `params` - anything you put into `params` dictionary will just get passed through:

    es.delete_by_query(index='b', params={'source': {"query": {"match_all": {}}}})

In the longer term I will add `DELETE` to the cases where `send_get_body_as` gets applied. (and possibly will rename it).

Note that even that's not a proper solution since a lot of proxies/libraries/servers don't allow URLs over certain length so there is no way of reliably support `delete_by_query` on app engine for all use cases (since we cannot use `POST` instead like for `GET` requests).

**Comment by barakcoh** [comment]
Thanks for the response, I'll give your workaround a try. You may want to consider re-adding the parameter to avoid breakage in other clients.
