### ISSUE TITLE
es.exists() documentation missing, behavior weird (or maybe just undocumented)

### ISSUE THREAD

**Issue by scaleoutsean** [elastic/elasticsearch-py#2386]
**Elasticsearch version** (`bin/elasticsearch --version`): 8.11.1

**`elasticsearch-py` version (`elasticsearch.__versionstr__`)**: elasticsearch-8.11.0

**Description of the problem including expected versus actual behavior**: es.exists behaves ambiguously - gives `False` when `True`, doesn't work with wildcards, and the [docs](https://elasticsearch-py.readthedocs.io/en/latest/api/indices.html#elasticsearch.client.IndicesClient.create) mention options that aren't available (`expand_wildcards=all`, `error_trace=True` and more).

**Steps to reproduce**:

- Wrong answer with exact match - responds with `False` for existing index
- Error with wildcard - (#643)
- Inconsistent behavior - gives `True` for one existing index

```python3
>>> es.exists(id=1, index='sean-syslog-2023-11-27-15')
HeadApiResponse(False)

>>> es.exists(id=1, index='sean-syslog-2023-11-27-*')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/.local/lib/python3.10/site-packages/elasticsearch/_sync/client/utils.py", line 402, in wrapped
    return api(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/elasticsearch/_sync/client/__init__.py", line 1494, in exists
    return self.perform_request(  # type: ignore[return-value]
  File "/home/ubuntu/.local/lib/python3.10/site-packages/elasticsearch/_sync/client/_base.py", line 320, in perform_request
    raise HTTP_EXCEPTIONS.get(meta.status, ApiError)(
elasticsearch.BadRequestError: BadRequestError(400, 'None')

>>> es.exists(id=1, index='sean-syslog-2023-11-27-*',expand_wildcards=all)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/.local/lib/python3.10/site-packages/elasticsearch/_sync/client/utils.py", line 402, in wrapped
    return api(*args, **kwargs)
TypeError: Elasticsearch.exists() got an unexpected keyword argument 'expand_wildcards'

>>> es.indices.create(index='sean-syslog-2023-11-27-15')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/.local/lib/python3.10/site-packages/elasticsearch/_sync/client/utils.py", line 402, in wrapped
    return api(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/elasticsearch/_sync/client/indices.py", line 493, in create
    return self.perform_request(  # type: ignore[return-value]
  File "/home/ubuntu/.local/lib/python3.10/site-packages/elasticsearch/_sync/client/_base.py", line 389, in perform_request
    return self._client.perform_request(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/elasticsearch/_sync/client/_base.py", line 320, in perform_request
    raise HTTP_EXCEPTIONS.get(meta.status, ApiError)(
elasticsearch.BadRequestError: BadRequestError(400, 'resource_already_exists_exception', 'index [sean-syslog-2023-11-27-15/Eveg1CE5SY2W85hX26Ghkg] already exists')
```

Maybe wildcards don't work by design and those outdated options don't apply, but why is `False` returned instead of `True`?

I also noticed I get `True` on one index, and `False` on two others. I created the "good" one manually and the other two from Python with `es.indices.create()` (just saying 0 replicas, which is the same number that the manually created index has). I appreciate that I may have used different options, but if `es.exists()` gives different answers depending on how an index was created, that should be documented.

![image](https://github.com/elastic/elasticsearch-py/assets/16622642/e3610d0c-7d84-415b-bc7f-63b970f8e25f)

**Comment by pquentin** [comment]
Hello! Sorry that using this API proved difficult.

I think the main issue here is that instead of using the [Exists API](https://www.elastic.co/guide/en/elasticsearch/reference/master/indices-exists.html) meant for indices and usable with `es.indices.exists` you're using the [Get API](https://www.elastic.co/guide/en/elasticsearch/reference/master/docs-get.html) in exist mode meant for documents and usable with `es.exists`. The `id` you're passing here is the id of the document, and Elasticsearch tells you if this particular document exists or not, not the whole index.

To help avoid this kind of confusion in the future (that I hit a lot myself), the next version of the documentation will be split into multiple pages:

 * main client with `es.exists`: https://elasticsearch-py.readthedocs.io/en/latest/api/elasticsearch.html#elasticsearch.Elasticsearch.exists
 * indices sub-client with `es.indices.exists`: https://elasticsearch-py.readthedocs.io/en/latest/api/indices.html#elasticsearch.client.IndicesClient.exists

Can you please try again with `es.indices.exists` and report back? Thanks.

**Comment by scaleoutsean** [comment]
`es.indices.exists` does work "as expected", thank you. You can close this issue.

For the context, [the .NET issue](https://github.com/elastic/elasticsearch-net/issues/3950#issuecomment-862178642) I mentioned was for `es.indices`, but I didn't notice that at the time.
