### ISSUE TITLE
Log progress in bulk helper utilities

### ISSUE THREAD

**Issue by pickypg** [elastic/elasticsearch-py#248]
In the bulk-related helpers, it would be nice to have some sort of checkpoint-based (e.g., every 1000) logging to acknowledge that something is still happening, as well as to give someone monitoring it the ability to get a rough idea of progress.

**Comment by HonzaKral** [comment]
This is mostly an issue for the `bulk` helper - my assumption was that if people cared about progress they'd use the `streaming_bulk` helper since it can be iterated on for reporting use case, see https://github.com/HonzaKral/es-django-example/blob/master/qa/management/commands/index_data.py#L28-L36 for an example of just printing dots every N documents.

Do you think logging should also be included?

**Comment by HonzaKral** [comment]
Closing this since there is a way around - either use `streaming_bulk` and roll any reporting you wish or rely on the standard logging of library where every `bulk` chunk will be logged.
