### ISSUE TITLE
Enable gzip,deflate headers to utilize `http.compression`

### ISSUE THREAD

**Issue by soundofjw** [elastic/elasticsearch-py#252]
Elasticsearch provides an `http.compression` setting for utilizing `gzip,deflate` as `accept_encoding`.

When using the `urllib3` Connection class, you may enable this manually as so:

```python
es = elasticsearch.Elasticsearch(hosts=hosts,
                                 **connection_settings)
connection = es.transport.get_connection()
connection.headers.update(urllib3.make_headers(accept_encoding=True))
```

**Comment by soundofjw** [comment]
Seeing the commentary on #241, I'd suggest that this could be implemented per request or global setting. :}

**Comment by HonzaKral** [comment]
I think this is better implemented by providing a custom connection class that adjust it's header in `__init__` after calling `super().__init__()`. Since it is relatively straightforward and only useful for a small number of use cases I'd prefer not to put it into the core.

We could definitely provide it in the docs as an example, what do you think?
