### ISSUE TITLE
A bit too hidden "ignore" parameter.

### ISSUE THREAD

**Issue by JulienPalard** [elastic/elasticsearch-py#274]
I'm trying pylint today, and reviewing my code with it, it shows a `Unexpected keyword argument 'ignore' in method call [E1123]`, when I call the `indices.create` method.

And it seems legit, the create method is defined as:
```
    @query_params('timeout', 'master_timeout')
    def create(self, index, body=None, params=None):
        """
        Create an index in Elasticsearch.
        `<http://www.elastic.co/guide/en/elasticsearch/reference/current/indices-create-index.html>`_

        :arg index: The name of the index
        :arg body: The configuration for the index (`settings` and `mappings`)
        :arg master_timeout: Specify timeout for connection to master
        :arg timeout: Explicit operation timeout
        """
```

There's no way here, even for the developper, to know that it's possible to give an `ignore` parameter here. [I know it's documented](https://elasticsearch-py.readthedocs.org/en/master/api.html#ignore), does documenting it here is enough to completly hide its existance in the methode where it's possible to use it ?

**Comment by HonzaKral** [comment]
That is a good question. I would say it's enough for it to be documented as a global parameter, especially since it is non-essential. I prefer this to the situation where all descriptions of the APIs have the few additional lines for `ignore`and other global parameters like `request_timeout`.

I will leave this ticket open for now to allow anyone who feels we should be more explicit to voice their opinions.

**Comment by HonzaKral** [comment]
Closing this since this is documented, feel free to comment with other suggestions.
