### ISSUE TITLE
Passing a non-integer as chunk_size to reindex breaks chunking

### ISSUE THREAD

**Issue by clintecker** [elastic/elasticsearch-py#308]
I was trying to run down a problem with why the `elasticsearch.helpers.reindex` function did not seem to be chunking properly.

Turns out I was passing "500" (string) as chunk size and the method did not break, but simply did the wrong thing (produced a single mega chunk).

I think calling `int` on `chunk_size` at the point of chunking (`helpers._chunk_actions`) would alleviate this confusion for future developers. Another option would be to raise an exception if we are not passed an integer, but I personally think libraries should try to be as liberal as possible in what they accept within reason.  

Obviously we don't want someone passing something other than a real integer or a stringified integer, but those eventualities can be handled specially.

**Comment by HonzaKral** [comment]
`chunk_size` is clearly marked as number in the docs. Python is a dynamic language so there isn't much else we can, or should, do here - there is always an option of passing an argument of different type and no guarantees that things will work as expected, or fail predictably.

**Comment by clintecker** [comment]
i think my major complaint is that when you do not pass an int the method
does not fail, does not warn you, and does not do the correct thing.

I get how Python works I just feel like there could be a better experience
because I wasted most of a day trying to figure out why the method was
"working" but not doing what it claimed to do.

**Comment by HonzaKral** [comment]
This is an issue of python dynamic nature where `"500"` is greater than integers. It is fixed in python 3, (you will get a `TypeError`). In the mean time I see no reason to strictly limit the types of a single parameter where it is absolutely clear from the description that it needs to be a number. Some people might even want to pass in something that is not a built-in number type (like `Decimal` or anything that is orderable with ints).

Sorry, this is just one of the pitfalls of dynamic languages.
