### ISSUE TITLE
How can I use more like this?

### ISSUE THREAD

**Issue by nelsonvarela** [elastic/elasticsearch-py#310]
The mlt method had been removed but I can not find a way to achieve the same. Can someone provide an example.

**Comment by HonzaKral** [comment]
There is now a more like this query that can serve instead of the api (https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-mlt-query.html) - just pass it into the `search` method in the body's `query` element and you should be good to go. If you need help constructing the body you can also have a look at the DSL library at http://elasticsearch-dsl.readthedocs.org/en/latest/

**Comment by nelsonvarela** [comment]
Thanks for your response! You helped me allot!
