### ISSUE TITLE
error information disregarded

### ISSUE THREAD

**Issue by prinsherbert** [elastic/elasticsearch-py#322]
In the file `elasticsearch/connection/base.py` around line 105 there is a function `_raise_error` which disregards a significant amount of the error message that the REST-api of elasticsearch returns (which can be found in raw_data)

This is information that could be crucial when debugging, and it's extremely annoying. A typical exception one may get is `TransportError(400, 'mapper_parsing_exception')` . The REST api tells you what went wrong exactly, but the python wrapper just tells you there's a mapper parser exception, form example:

    {
        "error": {
            "caused_by": {
                "reason": "Unexpected close marker ']': expected '}' (for OBJECT starting at [Source: org.elasticsearch.common.io.stream.InputStreamStreamInput@4c6b0892; line: 1, column: 14])\n at [Source: org.elasticsearch.common.io.stream.InputStreamStreamInput@4c6b0892; line: 1, column: 57]",
                "type": "json_parse_exception"
            },
            "reason": "failed to parse",
            "root_cause": [
                {
                    "reason": "failed to parse",
                    "type": "mapper_parsing_exception"
                }
            ],
            "type": "mapper_parsing_exception"
        },
        "status": 400
    }

Possible solution: decorate the TransportError with all information, for example the REST json returned.

**Comment by HonzaKral** [comment]
All the information from the body is passed on to the exception and available as the `info` attribute on it. Since it can be quite a large amount of data it is not represented in the exception's `repr`, it is still there however.

It is documented in the docs (http://elasticsearch-py.readthedocs.org/en/master/exceptions.html#elasticsearch.TransportError.info) but if there is anything else I can do to make it clearer please let me know. Thanks!

**Comment by prinsherbert** [comment]
That seems fair, thanks!
