### ISSUE TITLE
scan helper not thread safe?

### ISSUE THREAD

**Issue by veatch** [elastic/elasticsearch-py#341]
I hit a SerializationError when using the same client in a pool of multiprocessing processes and running scans.

```
pool = multiprocessing.Pool(processes=8)
pool.map(my_function, args)

def my_function(arg):
    resp = helpers.scan(my_app.es_client, index=..., doc_type=..., ...)
```
If I create a client inside each process, things work as expected:
```
def my_function(arg):
    client = Elasticsearch(...)
    resp = helpers.scan(client, index=..., doc_type=..., ...)
```
Am I wrong to expect to be able to do multiple scans with the same client?

**Comment by HonzaKral** [comment]
The client is thread safe, it is, however, not fork-safe. If you want to use the client in a multi process environment (which multiprocessing uses) you need to open a client in each process. The issue is that when a socket is open in one process which is then forked the forked process inherits the file descriptor so the two processes share one.

For more information see http://elasticsearch-py.readthedocs.org/en/master/#thread-safety

Hope this helps

**Comment by veatch** [comment]
Ok great, thanks. 

I just created #342 to clarify the thread safety docs. It might be a little redundant, but I think being more explicit would be helpful there.

**Comment by HonzaKral** [comment]
Thanks, I appreciate the clarification in the docs!
