### ISSUE TITLE
Connection timeout if port is unset/implied.

### ISSUE THREAD

**Issue by darylyu** [elastic/elasticsearch-py#352]
We spent a good amount of time to figure this out yesterday. Our elasticsearch host is proxied by nginx so when we try to access it we use `http://<username>:<password>@<ip_address>` in django-haystack, we get a timeout.

The problem went away when we explicitly set port 80. I'm under the impression that the problem is in elasticsearch-py mostly because the stack trace says so. We've tried using curl and httpie as our elasticsearch client and it worked fine.

I have some changes, but realized while updating the tests that it might be possible to access elasticsearch with another scheme. So I need feedback before continuing.

Is it safe to assume that es is only served either via http or https? I also don't know what the expected behavior is if the protocol/scheme is not included(example.com/_count instead of https://example.com/_count).

**Comment by corey-hammerton** [comment]
elasticsearch-py by default assumes http on port 9200 is used. If another port or scheme is used it must be specified.

**Comment by HonzaKral** [comment]
I am sorry for your frustration, but unfortunately there is no good solution here - people expecting the default port to be 9200 because we are talking to ES or people expecting the default to be 80/443 because http(s) both have a point.

We chose to err on the side of majority where people typically run elasticsearch without a load balancer on the default ports, which means 9200.
