### ISSUE TITLE
NotFoundError: TransportError delete_by_query

### ISSUE THREAD

**Issue by PREM1980** [elastic/elasticsearch-py#356]
I use the below query to clear all my documents but throws the below error - 

result = self.es.delete_by_query(
            index='tickets', doc_type='tickets', body='{"query":{"match_all":{}}}')

Error:
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
NotFoundError: TransportError(404, u'{"found":false,"_index":"tickets","_type":"tickets","_id":"_query","_version":1,"_shards":{"total":2,"successful":1,"failed":0}}')

**Comment by HonzaKral** [comment]
What version of `elasticsearch-py` and elasticsearch are you using? `delete_by_query` has been removed in new versions of elasticsearch (and moved into a plugin) which looks like this is the case - elasticsearch is interpretting the API as a delete document api.

**Comment by PREM1980** [comment]
elasticsearch==1.9.0

**Comment by HonzaKral** [comment]
For elasticsearch 2.x please use 2.x release of the client as well, this combination is not supported. `delete_by_query` api has been removed in elasticsearch 2.0. If you want to use this functionality you have to either install the plugin and call it manually using `client.transport.perform_request` or implement it yourself using a combination of `scan` and `bulk` helpers from elasticsearch.

recommended way is to organize your data so that you can always just delete entire indices, that is a much faster operation.

Thanks

**Comment by PREM1980** [comment]
Thanks for your quick response.

**Comment by zhihuiFan** [comment]
Here is an example suggested by HonzaKral. FYI

```
>>> es.search(index='test', doc_type='a', body={})
{u'hits': {u'hits': [{u'_score': 1.0, u'_type': u'a', u'_id': u'AVVHEn89Y_8AF_8mCE35', u'_source': {u'a': 2}, u'_index': u'test'}, {u'_score': 1.0, u'_type': u'a', u'_id': u'AVVHEasD2wAUojVaQdLb', u'_source': {u'a': 1}, u'_index': u'test'}], u'total': 2, u'max_score': 1.0}, u'_shards': {u'successful': 5, u'failed': 0, u'total': 5}, u'took': 70, u'timed_out': False}
>>> es.transport.perform_request('DELETE', '/test/a/_query', body={})
(200, {u'failures': [], u'took': 200, u'_indices': {u'_all': {u'deleted': 2, u'found': 2, u'failed': 0, u'missing': 0}, u'test': {u'deleted': 2, u'found': 2, u'failed': 0, u'missing': 0}}, u'timed_out': False})
>>> es.search(index='test', doc_type='a', body={})
{u'hits': {u'hits': [], u'total': 0, u'max_score': None}, u'_shards': {u'successful': 5, u'failed': 0, u'total': 5}, u'took': 32, u'timed_out': False}
```
