### ISSUE TITLE
exception in RequestError.__str__

### ISSUE THREAD

**Issue by gst** [elastic/elasticsearch-py#363]
this is with version 2.2.0.

I just got an "unprintable" (I mean str()) RequestError : 

>   File "/usr/local/lib/python3.4/dist-packages/elasticsearch/exceptions.py", line 55, in \_\_str\_\_
>     cause = ', %r' % self.info['error']['root_cause'][0]['reason']
> TypeError: string indices must be integers

effectively the _RequestError_ instance I received has an str within _**.info['error']**_  

this is reproducable.

do you need more info ?

**Comment by gst** [comment]
I see that the problem is because the server sends back an error which elasticsearch-py can't correctly parse (in `elasticsearch.connection.base.Connection._raise_error`).

```
        try:
            additional_info = json.loads(raw_data)
            error_message = additional_info.get('error', error_message)
            if isinstance(error_message, dict) and 'type' in error_message:
                error_message = error_message['type']
        except:
            # we don't care what went wrong
            pass
```

The `additional_info` I got is : 

```python
{
    'error': 'SearchPhaseExecutionException[Failed to execute phase [query], all shards failed ...CLEARED_FOR_CLARITY...', 
    'status': 400
}
```

but in `RequestError.__str__` there is :

```
        cause = ', %r' % self.info['error']['root_cause'][0]['reason']
```

but the info['error'] isn't a dict but a plain str, so TypeError ..

So either elasticsearch-py doesn't handle all errors possibilites here, or else the server doesn't send a valid error response..

I don't know which one is the more correct..

**Comment by HonzaKral** [comment]
Can you please make sure you are using the correct combination of `elasticsearch-py` and elasticsearch server? Looks like you are using 2.x version of the python library with 1.x server, which is not supported. Thanks

**Comment by gst** [comment]
@HonzaKral 

you just are right. just downgraded my client version to 1.9 and now the error is correctly printed/decoded.

If client 2.x is known to be problematic with 1.x server then shouldn't the client eventually verify that when it connects to the server and at least log a warning but I'd say preferably raise something if it detects that the server is not a 1.x one ?

**Comment by HonzaKral** [comment]
I don't think we can or should check for the version - I am a huge fan of the python philosophy of not performing checks like these (instead of `isinstance` checks rely on duck typing for example) and it can lead to some trouble in various scenarios - imagine someone running elasticsearch behind a proxy only exposing the `_search` endpoint. Then this check would always fail.

Unfortunately there isn't much we can do on top of documenting it properly. I am also reluctant to make this particular code work on both versions because the error leads people here.

Hope this makes sense

**Comment by prinsherbert** [comment]
IMHO code like this:

    cause = ', %r' % self.info['error']['root_cause'][0]['reason']

is fairly smelly, since one might drop relevant information in the `[1:]` part of the list. Often when I use the python client, exceptions miss relevant information that I do get when reproducing the call via `curl`.

Without much knowledge of the elasticsearch-py code base, I would suggest supporting multiple REST-API version error messages like this:

    cause = ', %r % (
        self.info['error']['root_cause'][0]
        if type(self.info['error']['root_cause'][0]) == str
        else self.info['error']['root_cause'][0]['reason'])

Assuming these are the only two error formats is tricky, nevertheless not trickier than assuming the format is `error.root_cause.0.reason`.

**Comment by HonzaKral** [comment]
There is only one error format for elasticsearch 2.0+ so we should be fine. The issue here was that people used `2.x` version of the library with elasticsearch `1.x` which is not backwards compatible.

I understand the concern with "hiding" the rest of the list, it is really just a compromise. To access the whole `dict` with the error details just access the `.info` attribute on the exception.

Hope this helps

**Comment by prinsherbert** [comment]
@HonzaKral sure, nevertheless debugging is often acting on exceptions that pop up. Reproducing an exception with inspection code can be a hassle, especially for hard to reproduce ones, or ones on production or even non-development deployments.

**Comment by HonzaKral** [comment]
I understand, but it can also go the other way around - exposing too much information in the `__str__` of the exception might lead to unwanted noise - some of the exception bodies can be quite huge. That's where we settled for a compromise to get one root reason and expose the rest via `.info`. Ideally that it what you should include in your logs when encountering elasticsearch exceptions.
