### ISSUE TITLE
Consider a faster json serialization library?

### ISSUE THREAD

**Issue by limdauto** [elastic/elasticsearch-py#365]
Hi, I was wondering if there has been discussion about using a faster json serialization library such as ujson (or rapidjson but it's not very backward compatible). It could speed up some APIs such as bulk indexing considerably. I haven't benchmarked it yet but just want to see if you are keen.

**Comment by HonzaKral** [comment]
Hi @limdauto, unfortunately not many of these json implementations are very stable in terms of error handling and other very important feature - `ujson` for example serializes `object()` as `{}` which can lead to very hard to find errors, `rapidjson` then throws a `RuntimeError` which could be very dangerous to try and catch.

For those reasons I don't see them as being implemented as part of the library any time soon. Especially since there is nothing stopping users from implementing the alternative serializers themselves:

```
class UJsonSerializer(object):
    mimetype = 'application/json'
    def dumps(self, data):
        try:
            return ujson.dumps(data)
        except:
            raise SerializationError()

    def loads(self, data):
        try:
            return ujson.loads(data)
        except:
            raise SerializationError()


es = Elasticsearch(serializer=UJsonSerializer())
```

**Comment by limdauto** [comment]
Thank you for taking the time to answer. The custom serializer solution looks great.
