### ISSUE TITLE
clear_scroll on reindex

### ISSUE THREAD

**Issue by cp2587** [elastic/elasticsearch-py#369]
Hi,

Thanks you very much for you work. 
I am trying the reindex helper function and i find it quite slow (~150 sec to reindex a very small index of 80k docs). 
Is is something normal - my cluster is made of 3 nodes (1 client and 2 data with each one 2GB ram)? How can i achieve better speed (i already set chunk_size to 1000)? 
It seems you don't call clear_scroll at the end of the reindex function (or after each successful scroll chunk retrieve), would it be useful to do it to speed-up the process ?

**Comment by HonzaKral** [comment]
Hi,

thanks for the issue. Calling `clear_scroll` is not required since the scroll will be cleaned automatically once all documents are retrievede at the end of the reindex. So if everything goes well the scroll will be cleared by elasticsearch as well.

It is very hard to say what causes the slowness in your case, note that the reindex API actually has to retrieve all the document over the network into your python process and then send them back into elasticsearch. All in single thread which can slow things down considerably.

Hope this helps,
Honza

**Comment by cp2587** [comment]
OK, i thought ES cleaned the scroll only after its timeout (5m be default on the python method).

Yes i guess there is a huge overhead of getting the data and sending them again :/ 
I will try using the multiprocessing or greenlet package to reduce this.

Thanks for the quick response. You can close the thread, i have my answers :)

**Comment by HonzaKral** [comment]
For sending the data in you can use the `parallel_bulk` helper, it uses threads to send data in parallel. Unfortunately there is no way to paralelize the scan easily.

There is currently some confusion whether scan is getting cleared automatically so I created an issue to clear it up - https://github.com/elastic/elasticsearch/issues/16929#issuecomment-191807048
