### ISSUE TITLE
Support for explicit closing and context managers

### ISSUE THREAD

**Issue by wdm0006** [elastic/elasticsearch-py#372]
In our usage of the library we have found some cases where it is useful to explicitly close connections.  It seems that this can be done with:

``` python
client = Elasticsearch()
for conn in client.transport.connection_pool.connections:
    conn.pool.close()
```

Likewise, it could be useful to use the client as a context manager, so something like:

``` python
with Elasticsearch() as client:
    client.foo()
```

And have the connections explicitly closed on exit.  It turns out that this can be done pretty simply and I have a working implementation in a feature branch [here](https://github.com/wdm0006/elasticsearch-py/tree/adding-close). In particular, the additions are 202-231 [here](https://github.com/wdm0006/elasticsearch-py/blob/adding-close/elasticsearch/client/__init__.py#L202). 

I've updated the one of the examples to include close, and added another to demonstrate the context manager behavior and it seems to be working nicely, at least for my purposes.  If there is interest, I'd be happy to make any changes and submit a pull request to fold this functionality into the library.

**Comment by royrusso** [comment]
+1 on fine-grained control of the connection pool.

**Comment by HonzaKral** [comment]
Can I ask, out of curiosity, what's the use case of wanting to close the connections explicitly?

We most likely won't implement a context manager, but a close method might make sense, though probably not on the client itself. Does `es.transport.close()` make sense to you?

Thanks!

**Comment by wdm0006** [comment]
One perhaps overly specific use case would be if you wanted to issue an elasticsearch query within a pyspark map.  Much of the time using something like elasticsearch-hadoop and then doing the processing in pyspark is more performant, but occasionally I've found cases where the queries for each row are sufficiently different and decoupled to where it makes more sense to have query per row in a map. 

If you do that, you have to open and close a lot of connections quickly (where normally maybe you wouldn't do that kind of thing), so waiting for the connection to get closed by gc is less than ideal.  We end up with much more reliable jobs in that case with the explicit closure shown above. 

As for adding it to transport vs. client, I could see adding it to both, but as a user, I'd rather interact with just the client when possible rather than have to munge around lower level objects, especially for something as high-level as this.  Any particular reason why not to include it at the client level (possibly in addition to transport)?

Also out of curiosity, why no context managers?

**Comment by HonzaKral** [comment]
Thanks for the answers, I appreciate the discussion!

> Any particular reason why not to include it at the client level (possibly in addition to transport)?

I don't want the method to be confused with an API call. Currently the client has only one attribute that is not directly representing an API (or an API namespace like `indices`). It's not a very strong reason, but I do believe that this is a very minority use case so I would like to err on the side of consistency (only API methods on client).

> Also out of curiosity, why no context managers? 

Because this is a VERY specific use case and for most cases this would be a very bad usage pattern that I do not want to promote or condone (even by just making it easier). I understand how useful it would be in your use case but I'd have to recommend to create a context-manager-wrapper around the client in your code.


The problem with opening connections is not just the overhead on the client level, but also on elasticsearch side. If you have any option of reusing a client by having a global singleton it should provide much better performance and stability. From what I can see (not familiar with spark at all, just googled) this is sometimes used in PySpark (https://github.com/apache/spark/blob/master/examples/src/main/python/streaming/sql_network_wordcount.py#L40-L43)

If you have a long running process, it is not good to keep reopening a connection to the cluster, if you have a short running script then it is a non-issue since the OS will clean up after the script ends.

@royrusso may I ask what is your use case for closing the connections explicitly?

**Comment by wdm0006** [comment]
Ok, that makes sense WRT client vs. transport.

For that particular pyspark case, yes, that global singleton would work for things outside of a map, but you cannot create RDDs inside RDDs, so for this particular use-case it wouldn't help you. 

I'll add the close to transport, remove the context manager portion and close from client, and open a PR if that sounds good.

**Comment by royrusso** [comment]
Will and I both work at Predikto. ;-)

Agreed that opening/closing connections is a costly operation, but in certain cases, developers would seemingly enjoy finer-grained control over the connection layer. I don't believe it causes harm to expose the function call... ?

We front ES with nginx, keeping persistent connections open to the ES cluster it proxies, so I'm not too worried about implications downstream. This is mainly an issue with starving Spark nodes due to open/lingering connections.

**Comment by HonzaKral** [comment]
@royrusso hm, it's still hard for me to imagine how you can have a long running python process (otherwise you wouldn't need close) and not be able to have a singleton instance. But as I know almost nothing of pyspark I of course trust you and will do my research :)

A PR with close() on transport would be nice, we just need to keep in mind that different connection classes can use different code so we need to also have a `close` method there as well (and probably also one on `ConnectionPool` to avoid accessing it's attributes from the outside).

I will be happy to do reviews or write the code myself soon if you don't feel like it.

Thanks!
