### ISSUE TITLE
Replace standard json serialization by ujson

### ISSUE THREAD

**Issue by philbb** [elastic/elasticsearch-py#378]
We should consider replacing the standard json serializer by ujson (aka ultrajson, C lib with Python bindings)

Reasons:
Attempting to index data that contains the type numpy.int64, for example, data that has been processed using Pandas, results in a TypeErrror : 
`TypeError: Unable to serialize 6 (type: <class 'numpy.int64'>)`

Advantages:
- can handle numpy.int64
- can handle pandas TimeStamp, datetime and date Python objects

Disadvantages:
- Adds a dependency

[feel free to add more...]

**Comment by HonzaKral** [comment]
The problem with `ujson` is that it isn't really stable andhas some weird behavior that can hide very important errors:
```
>>> import ujson
>>> ujson.dumps(object())
'{}'
```

If you want to use ujson, there is nothing stopping you from creating your own serializer object and passing it into the client (see #374 for an example). That's why I do not wish to include ujson as default.

I hope this makes sense.

**Comment by philbb** [comment]
Ok! Is there a current recommended / official way to insert data that's been processed in Pandas (and thus contains numpy.int64, etc) into elasticsearch?

**Comment by HonzaKral** [comment]
Currently it would be to either extend the serializer we have now to make sure it is aware of the type or use your own completely - if you are comfortable with `ujson` and certain about your data (since ujson will hide errors), use that.

If you would share your code (maybe just a gist?) implementing the ujson serializer I think many people would find it useful.

**Comment by lribeiro** [comment]
This works for me:

```python
from elasticsearch import Elasticsearch,JSONSerializer
import numpy as np
import json

class NumpyEncoder(JSONSerializer):
    """ Special json encoder for numpy types """
    def default(self, obj):
        if isinstance(obj, (np.int_, np.intc, np.intp, np.int8,
            np.int16, np.int32, np.int64, np.uint8,
            np.uint16, np.uint32, np.uint64)):
            return int(obj)
        elif isinstance(obj, (np.float_, np.float16, np.float32, 
            np.float64)):
            return float(obj)
        elif isinstance(obj,(np.ndarray,)): #### This is the fix
            return obj.tolist()
        return JSONSerializer.default(self, obj)

es = Elasticsearch(
    ['localhost'], serializer=NumpyEncoder()
)

```
https://gist.github.com/lribeiro/7d9fbedf830a54685811f63dbbce9464
