### ISSUE TITLE
Option to ignore warnings in connection classes

### ISSUE THREAD

**Issue by stickperson** [elastic/elasticsearch-py#418]
I'm using my own SSL certificate, so I have `use_ssl=True` and `verify_certs=False`. This triggers a [warning](https://github.com/elastic/elasticsearch-py/blob/master/elasticsearch/connection/http_requests.py#L57) (same if using `Urllib3HttpConnection`). Any objection to adding an `ignore_warnings` kwarg? Another option could be to have a `disable_warnings` function similar to that found in [urllib3](https://github.com/shazow/urllib3/blob/master/urllib3/__init__.py#L91).

**Comment by HonzaKral** [comment]
I am somewhat hesitant to disable the warnings, they are there for a reason. Even when using your own certificate you can just create your own CA and solve all the worries this way. Otherwise you are not really secure despite using SSL, hence the warning. 

Also it should only occur at startup as a log message, you can control the behavior of the warnings module, turning it off or redirecting it to the logging module which you can configure. Is that an option for you, to disable it on the python level?

Thanks!

**Comment by stickperson** [comment]
You're right-- I didn't realize it only occurred at startup. In that case I think it's fine to leave as-is. Thanks.

**Comment by tabascoterrier** [comment]
For fellow Googlers that come across this issue before the official docs - this can now be done with `ssl_show_warn=False`
