### ISSUE TITLE
Bulk Helpers : Add a max_wait_time field to trigger bulk after a period

### ISSUE THREAD

**Issue by seuf** [elastic/elasticsearch-py#480]
Hi,
Is it possible to add a `max_wait_time` to the streaming_bulk and parrallel_bulk helpers to trigger a bulk after a period event if less than `chunk_size` or `max_chunk_bytes` documents are generated ?
My action method is a kafka consumer, and when a reach the end of the topics i consume, I have to wait chunk_size messages before next bulk.

**Comment by HonzaKral** [comment]
Hi,

I understand the use case but I would like to avoid implementing timers like these. Do you think controling this from the outside might work for you? Something like:
```
def generate_docs():
    while True:
        try:
            doc = get_doc(timeout=500)
        except Timeout:
            break

while True:
    bulk(generate_docs())
```

I feel that this is sufficiently straightforward that it might work. What do you think?

thank you and my apologies for the late reply.

**Comment by seuf** [comment]
Ok, I will try this...

**Comment by HonzaKral** [comment]
Closing this issue as this is really not in scope for this library. Thanks for raising this issue.

**Comment by rohitgcs** [comment]
@seuf if you were able to implement this I would love to know how you did it because I don't see how to put a timeout on a kafka consumer (?)

@HonzaKral @fxdgear is there any particular reason we're not implementing a timer of some sort to the bulk api?
Something like a `timeout=True, max_wait_time =60` or `timeout=False`
Just trying to understand the issue since it will definitely be a popular use case for streamers.

**Comment by seuf** [comment]
@rohitgcs Sorry I don't remember I had sucess to implement this. the projects have moved direction since last year ans this lib is not more used.
