### ISSUE TITLE
use urllib3.PoolManager in Urllib3HttpConnection

### ISSUE THREAD

**Issue by timc13** [elastic/elasticsearch-py#500]
Have you thought about using `urllib3.PoolManager` instead of the individual pool classes in  `Urllib3HttpConnection`?  I think that would simplify some code and allow for the injection of a `PoolManager` class. 

My use case is that I would like to use the `AppEngineManager` described in the comments here https://github.com/shazow/urllib3/blob/master/urllib3/contrib/appengine.py

I wouldn't mind submitting a PR...

**Comment by HonzaKral** [comment]
Can you please elaborate in what code this would simplify? It looks like it would primarily add an extra step inside of `urllib3` to look up the adequate connection pool and add all the management of such classes.

We used the pool classes directly because that's what we actually want - a connection pool to a single host per each connection class in elasticsearch-py.

I would also be interested in hearing why you would want to use the `AppEngineManager` instead of the default way of running on app engine, is there any particular reason we should be looking at that?

Thank you!

**Comment by timc13** [comment]
you're right, it doesn't simplify anything.  I also figured out `AppEngineManager` is not necessary!  I think it is an older way of doing things, and Google has provided other options.
