### ISSUE TITLE
Using a GET request with a request body.

### ISSUE THREAD

**Issue by hgrimberg-sr** [elastic/elasticsearch-py#541]
It appears that the elastic search client uses a GET request with a body for the query DSL endpoint. I just discovered an issue with Google App Engine's HTTP fetching were the GET body is stripped. To my knowledge, the HTTP standard does not specify what should happen with a the body of a GET request provided it does not change the semantics of the request. The GET method makes sense since the query is an idempotent, (mostly) cache-able read request. 

Perhaps it would be better funnel the query DSL json through an alternative method or a parameter on the GET request? This would reduce the possibility of intermediary proxies doing strange things.

I filed a bug with Google to have them fix it on their end, but the client should not use non-standard functionality.

Issue with Google: https://code.google.com/p/googleappengine/issues/detail?id=13571

**Comment by HonzaKral** [comment]
There is a workaround for that in the client exactly because of app engine's limitation - http://elasticsearch-py.readthedocs.io/en/master/#environment-considerations

Alternatively you can try one of the add-ons that allow `elasticsearch-py` to use the app engine's `urlfetch` instead of the standard backend like https://github.com/Loudr/elasticsearch-urlfetch
