### ISSUE TITLE
Handle retry from back pressure 429 responses

### ISSUE THREAD

**Issue by nezda** [elastic/elasticsearch-py#556]
The `Transport` class has parameter `retry_on_status=(502, 503, 504, )`.  It would be neat if this class could retry on 429 as well, implementing the best practices of waiting with randomized exponential backoff and only resending failed work (outlined https://www.elastic.co/guide/en/elasticsearch/reference/master/tune-for-indexing-speed.html#_use_multiple_workers_threads_to_send_data_to_elasticsearch).

**Comment by HonzaKral** [comment]
Unfortunately we cannot do that as it could result in a very long and unpredictable requests. This is a low level client, the behavior you describe can only be used by specialized tools that have the option of weighing the risks and benefits such behavior brings.

Since we cannot make any assumptions on how this library will be used we cannot make such decisions.

That said it is relatively easy to wrap the client in some code that would implement this strategy:
```
for retry in RETRIES:
  try:
    client.some_method(...)
  except TransportError as e:
    if e.status_code != 429 or retry == RETRIES-1:
     raise
    time.sleep(2**retry)
  else:
    break
```

**Comment by nezda** [comment]
I just noticed this ultimately was added - cool!
https://github.com/elastic/elasticsearch-py/blob/2dce4c0720b529c1654e46246346bac660fdea9d/elasticsearch/helpers/__init__.py#L139-L142
