### ISSUE TITLE
msearch should be POST not GET

### ISSUE THREAD

**Issue by trevan** [elastic/elasticsearch-py#606]
The msearch request is sending GET as the method.  It should be POST as it is sending data in the post data.  Some proxies will strip out post data if the request is GET.

**Comment by HonzaKral** [comment]
If you have a proxy that strips `GET` data, please use the `send_get_body_as` parameter as mentioned by the configuration: http://elasticsearch-py.readthedocs.io/en/master/#environment-considerations

Thanks!

**Comment by bshibs** [comment]
@HonzaKral given that POST+body will work with more network middleware why isn't that the default?

**Comment by HonzaKral** [comment]
I believe it is nice to have APIs that only read data use the `GET` method so that you can easily distinguish in any network proxies/monitoring tools/... read traffic from write. Even potentially implement IP filtering or other more advanced methods.

**Comment by bshibs** [comment]
Thanks for explaining, @HonzaKral.  I'll make one more appeal.  Silently breaking known network topologies in the wild seems to violate the https://en.wikipedia.org/wiki/Robustness_principle.  You know you're breaking the former while you're making an assumption [1] about the utility of the latter.  That doesn't seem like a good trade-off.

[1] IMO it's a big assumption that your users are using HTTP method to distinguish read from write requests in their tooling rather than something more sophisticated.  Especially given that the msearch endpoint in question accepts both GET and POST.
