### ISSUE TITLE
Not able to skip the content from elastic search 

### ISSUE THREAD

**Issue by aankitkumar31** [elastic/elasticsearch-py#622]
i am using elastic search to get the content but when i set from its not skipping the records whereas size is working fine

 $params["body"]["from"] = 150;  // set from
   $params["body"]["size"] = 20; //set size

  $results = $this->_client->search($params);
            $result = $this->get_elastic_data($results);
            $total = $this->get_elastic_total_data($results);

please help me to get rid out of it.

**Comment by HonzaKral** [comment]
Hi @aankitkumar31, unfortunately I cannot help you since your problem is with the PHP client whereas this is a repository for the Python client. That said your code looks ok to me, the `from`/`size` pair should work just fine. If you decide to reopen your issue on elastic/elasticsearch-php repository please also include sample result or any reasons why you think the `from` is not working - is it returning the same documents? Do you have any sort order specified? What query are you using?

Thanks!

**Comment by aankitkumar31** [comment]
[index] => article
    [type] => article_mapping
    [scroll] => 1m
    [body] => Array
        (
            [query] => Array
                (
                    [bool] => Array
                        (
                            [must] => Array
                                (
                                    [0] => Array
                                        (
                                            [match] => Array
                                                (
                                                    [title] => modi
                                                )

                                        )

                                )

                        )

                )

            [terminate_after] => 15000
            [from] => 1500
            [size] => 2


i am setting thise values in parameters.

**Comment by HonzaKral** [comment]
You are specifying `scroll` which ignores `from` as it is used to unload all data from elasticsearch.

Also please do not continue the discussion here, it belongs to https://github.com/elastic/elasticsearch-php

Thank you!

**Comment by aankitkumar31** [comment]
ok thanx
