### ISSUE TITLE
Index single type index

### ISSUE THREAD

**Issue by shaytidhar** [elastic/elasticsearch-py#646]
Since elasticsearch 6 may contains only single type index, type should not be a mandatory parameter when indexing or updating.
https://www.elastic.co/guide/en/elasticsearch/reference/5.6/removal-of-types.html

**Comment by fxdgear** [comment]
Agreed. But since there's some backwards compatibility issues to be taken into account. Also to note the `doc_type` is not going away in 6 it can only be a single value per index. I don't want to make assumptions as to the "doc_type" name that people will use. 

As of ES 6.0 the doc_type is still required when creating an index, but there can only be 1. 

https://www.elastic.co/guide/en/elasticsearch/reference/6.0/indices-create-index.html#mappings

**Comment by pudo** [comment]
This really isn't great: we've now removed doc_types from our system, but still need to pass around magic values which have no meaning or purpose to every write call of the index. Can there not be some sort of 6.x default doc_type name?
