### ISSUE TITLE
Parallel queries for a long result

### ISSUE THREAD

**Issue by juandasgandaras** [elastic/elasticsearch-py#680]
I need to get a long list of registers from Elasticsearc with elasticsearch.py or elasticsearch-dsl.py. 

For a small results works fine but for example if I want retrieve a long result from Elasticsearch (more than 2000 registers)  it is so slow and takes a long time.

I am using somthing like this:

        s = es.search()
        s = s.query(my_query)
        s = s.source()

        res = [h.id for h in s.params(size=100).scan()] 

I was thinking about to use  a Pool from  from multiprocessing library, but doesn´t work correctly and Elasticsearch doesn´t retrieve a complete result and at the end I don´t have all the registers that I retrive in the query to Elasticsearch.

Could somebody tell me something about this? Thanks in advance

**Comment by WisdomPill** [comment]
The scan returns an iterator and you're using it inside of a list comprehension which tries to create a list, but to create a list python tries to resolve all the items from the iterator e=which in your case are too many. With 2000 results it works the same but you don't notice it since the results are too little.
I would suggest to use a for and add the results to a variable outside of the for context.
For parallel queries a would give a try to sliced scroll API, checkout the following link https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-scroll.html#sliced-scroll

Hope it helps.

**Comment by juandasgandaras** [comment]
Thanks for your help!!

**Comment by fxdgear** [comment]
@juandasgandaras if you have any other problems please feel free to re-open. 

@WisdomPill Thanks again for all your help! :smile:
