### ISSUE TITLE
Broken pipe exception during bulk insert

### ISSUE THREAD

**Issue by chan0415** [elastic/elasticsearch-py#692]
I am using AWS Elasticsearch (5.5) for my task. For entry level nodes, AWS ES has a HTTP payload limit of `10MB`. Therefore I am using following setting in the `bulk` API which is using `streaming_bulk` under the hood.

~~~
res = helpers.bulk(es, actions, max_chunk_bytes=9000000)
~~~

This works perfectly fine until I pass a huge file of the size `14MB`. I am getting `broken pipe` exception. To be exact, this is the error message I am getting:

~~~
2017-12-31 03:56:39,631 WARNING POST https://<aws_es_endpoint>:443/_bulk [status:N/A request:0.345s]
Traceback (most recent call last):
  File "elasticsearch/connection/http_requests.py", line 76, in perform_request
  File "requests/sessions.py", line 576, in send
  File "requests/adapters.py", line 426, in send
ConnectionError: ('Connection aborted.', error(32, 'Broken pipe'))
~~~

I found several [workarounds](https://stackoverflow.com/a/16865106) in StackOverflow for broken pipe exception, but nothing specific to Elasticsearch.

How can I fix this issue. One possible option is split the huge files into chunks of  `<10MB`. But I assume, its already taken care by the `streaming_bulk` API when we specify `max_chunk_bytes` parameter.

**Comment by HonzaKral** [comment]
Unfortunately there is nothing we can do since this is not an issue with `elasticsearch-py` - see https://github.com/requests/requests/issues/2422#issuecomment-91741465 for details - `requests` backend doesn't handle unfinished connections well. It looks like a single document is larger than the limit, `streaming_bulk` cannot separate a single document into multiple requests, you would have to do it yourself and split it into multiple `update` operations adding fields gradually if possible.

The correct solution here is to raise the request size on the elasticsearch side.

Hope this helps
