### ISSUE TITLE
Installation fails on Python-2.6.6 via pip install

### ISSUE THREAD

**Issue by feetdust** [elastic/elasticsearch-py#787]
~/Work/P/EH]$ pip install elasticsearch
Traceback (most recent call last):
  File "/home/jit/Work/P/EH/EHHVENV/bin/pip", line 7, in <module>
    from pip._internal import main
  File "/home/jit/Work/P/EH/EHHVENV/lib/python2.6/site-packages/pip/_internal/__init__.py", line 42, in <
module>
    from pip._internal import cmdoptions
  File "/home/jit/Work/P/EH/EHHVENV/lib/python2.6/site-packages/pip/_internal/cmdoptions.py", line 16, in
 <module>
    from pip._internal.index import (
  File "/home/jit/Work/P/EH/EHHVENV/lib/python2.6/site-packages/pip/_internal/index.py", line 526
    {str(c.version) for c in all_candidates},
                      ^
SyntaxError: invalid syntax

**Comment by feetdust** [comment]
Tried on Python 2.7.13 doing a pip install it works.

**Comment by untergeek** [comment]
I'm not sure if we'll try to address this or not, but I would not use Python 2.6 in anything, since it is no longer supported by the Python organization.  It is deprecated and should not be used, regardless of whether or not an older operating system is using it.  An increasing number of dependency modules will likely stop working with 2.6 due to some of these deprecated syntaxes.

Python 2.7 even has a [countdown timer](https://pythonclock.org/) before it is completely deprecated.  It's time to move on.

**Comment by feetdust** [comment]
Please do update the setup.py accordingly. Else on PyPI (https://pypi.org/project/elasticsearch/) it shows support for Python 2.6. Thanks @untergeek .

**Comment by fxdgear** [comment]
Thanks for raising this is an issue, but unfortunately this is out of our control as the real issue is with pip not elasticsearch-py. 

If you look at the trace back this is an error in pips code.
