### ISSUE TITLE
"scroll" keyword has a vague name and lacks documentation

### ISSUE THREAD

**Issue by JonathanHourany** [elastic/elasticsearch-py#814]
When trying to understand how to best use `helpers.scan` I was very puzzled by the `scroll` keyword. For quick reference, here's the function signature:
```
scan(client, query=None, scroll=u'5m', raise_on_error=True, preserve_order=False, size=1000, 
request_timeout=None, clear_scroll=True, scroll_kwargs=None, **kwargs)
```

 I now understand that it has to do with how long minutes to keep the view open, but here's why I think it has some problems with the way it is right now:

1. **"Scroll" as a name doesn't tell us what the argument does.** Unless "scroll" is commonly understood to mean 'view time' in the search world, argument name itself could mean anything. A better name would be `view_time` or `consistant_view_time` or really anything that implies that the argument is a time parameter.

2. **The default parameter doesn't help.** The "m" in "5m" could just as well mean "millions" It doesn't allude to "minutes" and we can't infer it since other units aren't offered in the documentation. Is "h" acceptable for hours? How about "s". How granular can we get? Is "1.53m" acceptable? If only minutes are acceptable, then why is the argument a `str` instead of `int`

3. **The documentation is terse**. Again, now that I know scroll is related to time, when reading
>Specify how long a consistent view of the index should be maintained for scrolled search

it's obvious what it's talking about, but if you don't know that this is a time parameter then "long" could very well be interpreted as having something to do with the amount of results. That the `size` is the batch size while `scroll` is the total number of results.

Though I think changing the name of the parameter and an expansion of the documentation about acceptable params would be best, really, alluding to time in any point would make this parameter a great deal more understandable

**Comment by fxdgear** [comment]
@JonathanHourany I'm sorry to hear you're having some difficulty with the naming of the parameters. 

unfortuanly I'm not going to change it. And I'll tell you why. :)

If you look at the Elasticsearch docs for the [Scroll API](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-scroll.html) you will see that `scroll` is used as the parameter for Elasticsearch. And as such I want to keep parity of the naming convention with Elasticsearch as well as the values for each parameter. 

```
POST /twitter/_search?scroll=1m
{
    "size": 100,
    "query": {
        "match" : {
            "title" : "elasticsearch"
        }
    }
}
```

Also the `scan` helper references itself as an abstraction around `elasticsearch.Elasticsearch.scroll` if we nav to the doc string for that function: https://github.com/elastic/elasticsearch-py/blob/52006f45620780046a0c7a2dfdf5777c3e4bfebc/elasticsearch/client/__init__.py#L993-L1001

You can see that it references the Elasticsearch Scroll API Documentation so that you can understand more about how the Scroll API works. 

This client is meant to be pretty thin. 

I hope this explanation helps.

**Comment by JonathanHourany** [comment]
Thanks @fxdgear 
>If you look at the Elasticsearch docs for the Scroll API you will see that scroll is used as the parameter for Elasticsearch. And as such I want to keep parity of the naming convention with Elasticsearch as well as the values for each parameter.

Ah, I didn't realize that ES itself uses this naming convention. In that light, I totally agree with not changing it then. Maybe I should take my bullet points to them instead! 😆 

I appreciate the link to the Scroll API and pointing out that reference to it is made in the scroll function. It clarifies a lot of things, and it's looks like I glazed over it when scanning the docs. In that case, I can understand why a change to the parameter isn't necessary. Thanks for taking the time out to respond 😃

**Comment by fxdgear** [comment]
:) you're welcome!

**Comment by KrishnaChaitanya-Gopaluni** [comment]
The accepted units for scroll, can be found here: https://www.elastic.co/guide/en/elasticsearch/reference/current/common-options.html#time-units
And, I suppose, information on this issue can be helpful : https://github.com/elastic/elasticsearch-dsl-py/issues/796
