### ISSUE TITLE
how to set version using RPM ?

### ISSUE THREAD

**Issue by mrmobo** [elastic/elasticsearch-py#837]
Hi Guys, 

I installed Elasticsearch-py from the following: https://centos.pkgs.org/6/epel-i386/python-elasticsearch-1.9.0-1.el6.noarch.rpm.html

Getting a "406" error I think it is because it is using the wrong version.  In the documentation it shows that we could pick the version via requirement.txt or setup.py.  

My problem is.. I am in an environment with no network connection, I don't have Pip and I am using Python 2.6.6.  

Please help!

**Comment by mrmobo** [comment]
Is there a way to set the Version manually? maybe by modifying something in the site-packages folder?

**Comment by fxdgear** [comment]
Ouch. I'm sorry you're having issues. This is unfortunate. 

So going thorugh setup or requirements etc. won't fix the problem for you cause you are in an environment with no network connection. 

You have installed a VERY VERY old version of the client. 1.9.0. 

My recommendation would be to go to PyPI and download a tar of the version you want using the computer you're using now (to write this issue since I know you can connect to the internet with it).  Then somehow you can copy the tar file to your server. 

Depending on the version of Elasticsearch you're using you should pick the version below that most closely matches:
* [elasticsearch 6.x](https://pypi.org/project/elasticsearch/#files)
* [elasticsearch 5.x](https://pypi.org/project/elasticsearch5/#files)
* [elasticsearch 2.x](https://pypi.org/project/elasticsearch2/#files)
* [elasticsearch 1.x](https://pypi.org/project/elasticsearch1/#files)

**Comment by hellysmile** [comment]
I am using this tool https://github.com/jordansissel/fpm to pack rpms my own

**Comment by sethmlarson** [comment]
This issue seems solved. If there are still issues please reopen.
