### ISSUE TITLE
can gracefully handle NaN and NaT by replacing them with None while handling bulk request

### ISSUE THREAD

**Issue by anjsudh** [elastic/elasticsearch-py#861]

**Comment by kutty-kumar** [comment]
@anjsudh can you please give an example for this, please elaborate on what issue you are facing exactly with steps to reproduce the same.

thanks

**Comment by sethmlarson** [comment]
NaN and NaT have mixed semantics (either missing value which maps properly to `None` but also can be the result of a floating point operation. Instead of making a decision here for users in order to maintain maximum customizablility users can make this decision on their own by providing a custom serializer:

```python
import pandas as pd
from elasticsearch import JSONSerializer, Elasticsearch


class CustomJSONSerializer(JSONSerializer):
    def default(self, data):
        if pd.isna(data):
            return None
        return super(CustomJSONSerializer, self).default(data)


es = Elasticsearch(serializer=CustomJSONSerializer())
```
