### ISSUE TITLE
socket timeout after a period of time

### ISSUE THREAD

**Issue by javixeneize** [elastic/elasticsearch-py#869]
Hi

I have a flask application that writes in elasticsearch when an endpoint is hit.

I have noticed that, after a period of time, i start having timeouts when connecting to elasticsearch. If i stop the application and start it again, it works fine. 

I start the elasticsearch connection only when i start the application, and when i hit the endpoint, i just ingest the data in the elasticsearch instance i have created

Any idea what could the the problem here? Would it be better to open and close the connection every time i want to ingest data in elasticsearch? I think this would solve the problem, but i fear it will kill the performance

Thanks

**Comment by fxdgear** [comment]
There's a few different ways to handle this and of course it all depends on your data your use case and your load. 

So the first answer: 

Yes you're better off recreating the Elasticsearch client object each time you want to index data. Elasticsearch communicates of HTTP, and as such there's no need to create long lived connections. 

Next thing to think about is your load and requests per second.If you're getting a lot of requests per second then you might be better off instead of having a blocking request on your website to queue up all these docs you want to index into elasticsearch into something like redis/rabbitmq and then do some bulk indexing. 

This would mean a bit of a re-arch of your project to accept an http request then populate the document  on a queue. Then you can have a queue consumer which reads documents off the queue and instead of indexing 1 document per request you can take a bulk of lets say 10 or 100 or 1000 documents off the queue and then use the `helpers.bulk` to index the documents in one request to ES. 

I hope that helps.

**Comment by javixeneize** [comment]
Yes, that’s really useful. I understand I have to open a connection and
close it in every request then. I will give it and try and compare results,
latency etc...

Traffic is low, it’s just a personal app I will use like 50-100 times per
day

Thanks!

**Comment by fxdgear** [comment]
:+1:
