### ISSUE TITLE
`elasticsearch6` 6.4.1 depends on `elasticsearch`

### ISSUE THREAD

**Issue by anthonywittig** [elastic/elasticsearch-py#951]
Hello,

In 6.4.1, client/xpack/__init__.py line 1 has 

```py
from elasticsearch...
```

should this be the following?

```py
from elasticsearch6...
```

It looks like there might be a few places that need updating.

**Comment by john-parton** [comment]
I'm also experiencing the same problem.

I tried doing a `pip install elasticsearch6` and also `pip install https://github.com/elastic/elasticsearch-py/archive/6.4.0.zip` (to install directly from the releases page) and both had the issue.

I was hoping to upgrade to the `6.4.X` branch so that I could get the fix for `max_chunk_bytes`.

**Comment by fxdgear** [comment]
Thanks for the patch. Having jenkins go over it now.
