### ISSUE TITLE
How to avoid EsRejectedExecutionException while using parallel bulk API

### ISSUE THREAD

**Issue by zealot-shin** [elastic/elasticsearch-py#978]
I'm trying to use parallel bulk API to save data into es.
But I find that when using parallel bulk, elasticsearch will throw EsRejectedExecutionException, cause:
"
Caused by: org.elasticsearch.common.util.concurrent.EsRejectedExecutionException: rejected execution of org.elasticsearch.ingest.IngestService$4@74222694 on EsThreadPoolExecutor[name = node-2/write, queue capacity = 200, org.elasticsearch.common.util.concurrent.EsThreadPoolExecutor@74d78408[Running, pool size = 8, active threads = 8, queued tasks = 284, completed tasks = 113506]]
"

which means es cannot handle these too many bulk tasks.
From the parallel bulk API, we can see that the default thread count and queue size is both 4. 
Even if I set  these two params to 2, EsRejectedExecutionException still occurs.
So I'm wondering if there is a way to avoid EsRejectedExecutionException while using parallel bulk.

**Comment by Winterflower** [comment]
Hi @zealot-shin - is this an issue with your ES cluster or with Python client `elasticsearch-py` library? Are you getting any exceptions from the Python client itself? If not, this is probably not the right repo for questions about Elasticsearch's ability to handle/not handle these bulk tasks.
If you have a problem with how the Python client is working, please show us a minimal example of what you are doing in the Python code and any exceptions, errors and/or stackstraces you are getting when trying to use parallel bulk. 
Otherwise, please use the discuss forums https://discuss.elastic.co/ or see this blogpost - perhaps it can answer your question about bulk rejections https://www.elastic.co/blog/why-am-i-seeing-bulk-rejections-in-my-elasticsearch-cluster
Thanks!

**Comment by zealot-shin** [comment]
it seems like there's no exception from the Python client itself.
here is how i use the parallel bulk:

`try:
                self.loger.debug('begin to parallel bulk %s data into es.' % len(es_data))
                for ok, info in parallel_bulk(
                        client=self.es_client, actions=self.gendata(es_data),
                        thread_count=self.args["thread_count"], queue_size=4, request_timeout=30,
                        chunk_size=self.args["chunk_size"],
                        max_chunk_bytes=self.args["max_chunk_bytes"] * 1024 * 1024,):
                    if not ok:
                        self.loger.error('failed to parallel bulk: %s' % str(info))
            except Exception as e:
                self.loger.error("error while parallel bulking with exception: %s." % str(e))
            self.loger.debug('parallel bulk finished')
`

while saving data into es, request timeout exception sometimes occurs. 

Since when using parallel bulk, I can see the thread pool info of es cluster from the cat API:
curl localhost:9200/_cat/thread_pool?v | grep -v master |  grep "write\|flush"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
101  3640  101  3640    0     0   716k      0 --:--:-- --:--:-- --:--:--  888k
node-1    flush                    2     1        0
node-1    write                    2     0      511
node-2    flush                    1     0        0
node-2    write                    4     6      128

sometimes the queue continuesly increase until it reaches 200, thus EsRejectedExecutionException happens.

in my occasion, i wanna know how I can control the parallel bulk's behaviour in order to avoid EsRejectedExecutionException.

**Comment by zealot-shin** [comment]
Since it's not elasticsearch-py's problem, close
